language: node_js
os:
- linux
- osx
node_js:
- '8'
install:
- npm install -g esy@0.1.32
script:
- make bootstrap
- make ESY_RELEASE_TAG="$TRAVIS_TAG" platform-release
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CiT1IlI4KANi/VOw+7N4CKxQyiaISjDQWqgOSCXdCrRCsXG9NQfdOf4Hu0f2TRTqS1G4gfwRMZSoIIUSDa45L1iwHdjUd6/shV5n+v+5yMSz7kndO0xEt5TmZPw0m3d2d1/D5vrYpmKHtMSkH294WX7mnheRb8WFaWwKrbbF44F7RUoTIyjvBXhacYPKoV3xVuKdYyd3s1S7YPR0Eb6xQTQ2/2KtFaU3PdUoMr9ixTSDsI5fq8HFVbRnsI2TwYoe6HG3oi3PuMmuYI3TX0BDnnd4CPi+FVuMQ3DWJcecvZNtW5HOjDWVZYZaQX5ypMMnewOZD6Gmu3eYR7snkeIBe/SPuqqI8bm2F73xJ/YN2Lt91rBjMo+rmzFpgidO954/WKoM2jrNtIfZ/4AAxokfmINSZeoUwQJt5RxVuja/DtD/WkMfNqHTWYeP5I40Pimj30Ocay5cJoomFMJRrSHrMEgaiamTtjtPm9xJFFjkvkll1fi2Cu07ma4pVPnVAa7JQ8/G7lFyeoVCdMEeF0ymTm8s2duUcmBt9k4kJHxW4c2/5SJDPNgcQkyN/CEbTo26gzIJ4XpXpNDSuE72M3QPvqb49D33qu1ktCxpBruKonmIzbD7jku2f9qhEqf0LrdnoZwWrHieWLoEIV6Uupb/4hDTQN3XGt3t0oBZJXTeWO0=
  file_glob: true
  file: _platformrelease/esy-solve-cudf-*-*.tgz
  on:
    repo: andreypopp/esy-solve-cudf
    tags: true
