language: node_js
os:
- linux
- osx
node_js:
- '8'
install:
- npm install -g esy@0.1.32
script:
- make bootstrap
- make ESY_RELEASE_TAG="$TRAVIS_TAG" platform-release
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NAyhpbDEatR188XFtvXd0NNY32inSKkCF8tzSyMl/74SIeiEFizKRXO/cWhJciyA/VdDnSi0ZUt27ZhevQzM5eTStV5PDkGpGQoPtZO8EfdsZlcLW/eRR9BoysYYVkSabaUmOzeXn9mZ8xJxmdiygBtjCGxvN4CZYSbV996N4eoMT86rsEEVlchwcTnVLunywkcdOocbtnCZpiw7by5h/yuGWsuhB6ij76ygDDR/DKvMTuzUci0tPPyjUFjhzWajF9Xewgo8i0+aanJZVb6oP67K0LEzVn1OOTc40NTdJQH9D09SA4cIYM2wvc0dt2LC5IwLwllflpqgy6AY7xw67kKdhpNk5GrwJ/6SuPemUvAHXmJbbXP7SBoFywYVY/ZK79I0NTW9lv265/lsaY7KMRN8WDP7zp13x+O+TZuItWdYyOOfVUleXFR+935ime3eeES+Xh6CoGpRsH/lCjItnEzqbvpJkC4KqMaGp2jlPr54gIn/9bzFd3rATD4GG9yJYx9UPFOhNV4zLtYLLtV3tp7fAYTgp2Z3w19OZ/IiAGWypfoLxgFHfbSAjtTuwqzV46F8k7Zzz7Tuyt1DGFrIkPKfj60oQhkI2TGQ+HkvldtODQnvohdZFDTr8BYXZCAt1Fj/2Tklu2NesnNL8wrgXnwJbHs1Tf70rkDiSCOPN5k=
  file: _platformrelease/esy-solve-cudf-*-*.tgz
  file_glob: true
  on:
    repo: andreypopp/esy-solve-cudf
    tags: true
